name: Data Retrieval Request
description: Retrieve my old files stored in my Datahub account. This request is no way related to retrieving files stored in Github repositories. These requests will be processed within 5-10 business days.
title: "Request my old files stored in Datahub"
labels: ["support", "data retrieval"]
assignees:
  - balajialg
body:
  - type: markdown
    attributes:
      value: |
        Please follow the sections in the template and provide us the information required to retrieve your files!
        
        > [!WARNING]
        > **FERPA Compliance:** Please remove or crop out any names, usernames, or email addresses from screenshots.
  - type: textarea
    id: email
    attributes:
      label: Your UC Berkeley Email Address
      description: "Please enter your official UC Berkeley email address! eg: oski@berkeley.edu. Instructions on how to retrieve your files will be sent to this email address."
    validations:
      required: true
  - type: textarea
    id: link
    attributes:
      label: Link to Your Datahub Folder
      description: "Please enter the link to your datahub folder. You can find the link at the bottom of the WHERE-ARE-MY-FILES.txt file in your Datahub home directory. Eg: gs://ucb-datahub-archived-homes/your-folder-path"
    validations:
      required: true
